# Generated by Django 6.0.4 on 2026-05-04 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analysisresult_id'),
        ('data_ingestion', '0005_dataset_processed_rows_dataset_total_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField()),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ingestion.dataset')),
            ],
        ),
    ]
