# Generated by Django 6.0.4 on 2026-05-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_cleandatarecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='distributions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='trends',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
