# Generated by Django 6.0.4 on 2026-05-09 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analysisresult_distributions_analysisresult_trends'),
        ('data_ingestion', '0006_dataset_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='distributions',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='trends',
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ingestion.dataset'),
        ),
    ]
