# Generated by Django 6.0.4 on 2026-05-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0006_dataset_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='sheet_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
