# Generated by Django 6.0.4 on 2026-05-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0006_dataset_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('bi_insights', models.JSONField(blank=True, default=dict)),
                ('predictions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ingestion.dataset')),
            ],
        ),
    ]
