# Generated by Django 6.0.4 on 2026-05-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0006_dataset_completed_at'),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='insight',
            old_name='bi_insights',
            new_name='dashboard_data',
        ),
        migrations.RenameField(
            model_name='insight',
            old_name='summary_text',
            new_name='raw_ai_response',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='predictions',
        ),
        migrations.AddField(
            model_name='insight',
            name='ai_model',
            field=models.CharField(default='groq', max_length=100),
        ),
        migrations.AddField(
            model_name='insight',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='data_ingestion.dataset'),
        ),
    ]
