# Generated by Django 6.0.4 on 2026-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_alter_insight_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insight',
            old_name='contents',
            new_name='summary_text',
        ),
        migrations.AddField(
            model_name='insight',
            name='bi_insights',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='predictions',
            field=models.JSONField(null=True),
        ),
    ]
