# Generated by Django 6.0.4 on 2026-06-02 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0007_datarecord_sheet_name'),
        ('insights', '0003_insight_bi_insights_insight_predictions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('response_source', models.CharField(default='ai', max_length=20)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='data_ingestion.dataset')),
            ],
        ),
    ]
