# Generated by Django 6.0.4 on 2026-05-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_rename_contents_insight_summary_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='contents',
            field=models.JSONField(null=True),
        ),
    ]
